### ISSUE TITLE
Translation the README.md to english , spanish and french 

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#1]
Hi . I create this project two moths ago, and it will be very cool if it could be translated to english , spanish and french.
Start with the README.md for now.
Thanks and have a nice hacktoberfest 2020

**Comment by MilePaor** [comment]
Can i take this one? @adalbertobrant

**Comment by shehrozsheikh** [comment]
Just created a PR, please have a look and let me know if there's an issue -> https://github.com/adalbertobrant/metabolismobasal/pull/3

**Comment by adalbertobrant** [comment]
Hi @MilePaor I´ve just go this pull request from @shehrozsheikh maybe you should work together in this one.

**Comment by MilePaor** [comment]
Thanks @adalbertobrant , ill let @shehrozsheikh finish this PR :)

**Comment by Sandradell** [comment]
Hi! Can I do spanish ?

**Comment by adalbertobrant** [comment]
Come on guys need some stars @shehrozsheikh @MilePaor @rodbv  @fsenaweb

**Comment by shehrozsheikh** [comment]
Done!
