### ISSUE TITLE
Faça a calculadora de indice corporal

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#11]
Olá seja bem vindo ao hacktoberfest.

Lembre-se de colocar uma estrela nesse repositório.

Que tal agora ler o README.md e perceber que não foi feito ainda a calculadora de índice corporal?

Crie um novo diretório , coloque a calculadora lá utilizando css, html5 e javascript.

Super Hacktoberfest 2020 para todos. 

Qualquer dúvida me envie uma mensagem.

**Comment by rodbv** [comment]
Opa!
Vou mandar um PR pra isso :)

**Comment by adalbertobrant** [comment]
Muito obrigado ai Brother, você é TopZera @rodbv

**Comment by rodbv** [comment]
Valeu cara! parabens pela iniciativa pros  marujos de 1a viagem no  Hacktoberfest como eu :)

**Comment by adalbertobrant** [comment]
> 
> 
> Valeu cara! parabens pela iniciativa pros marujos de 1a viagem no Hacktoberfest como eu :)

Ah Brother, muito obrigado Você pelas contribuições e ensino de como melhorar o código. Valeu Demais.
