### ISSUE TITLE
Fix calculator/page for Metabolismo Basal

### ISSUE THREAD

**Issue by rodbv** [adalbertobrant/metabolismobasal#16]
Apparently the calculator/page for basal metabolism is not working anymore (bad merge?)

**Comment by adalbertobrant** [comment]
Hi Rodbv , thanks to issue this and that is true , I think in some pull request I guy messed with my config , please , fix it.

**Comment by adalbertobrant** [comment]
Hello @rodbv someone messed my calculator , could you gimme a hand or maybe some of your friend which not have yet all 4 pr´s?

**Comment by rodbv** [comment]
Sorry mate I'm a bit in trouble these days at work.
I recommend you check how you're merging the PRs as it's not the first time it overwrites old code, it will happen again if you don't figure this out.
