### ISSUE TITLE
Add licence and code of conduct information

### ISSUE THREAD

**Issue by rodbv** [adalbertobrant/metabolismobasal#18]
It's good for any open source project to have a licence and a code of conduct file.

Here's a good example of a Code of Conduct file https://github.com/okfn-brasil/querido-diario/blob/main/CODE_OF_CONDUCT.md

..and here's a good explanation why it's important to have one: https://docs.github.com/pt/free-pro-team@latest/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by rodbv** [comment]
Feel free to assign it to me if you want I can take care of those :) 
For Licence I suggest MIT https://www.diegobrocanelli.com.br/open-source/a-licenca-mit/

**Comment by adalbertobrant** [comment]
Hi Rodbv, great idea , thanks for the super help.
