### ISSUE TITLE
Translate the web to english , spanish and french

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#2]
Hello my friends!

Just translate the index.html file to english , spanish and french

Create a link in the top right in index.html to english, spanish and french translation .

Do not use google translation.

**Comment by wojciechwachowiak** [comment]
can you assign this to me?

**Comment by shehrozsheikh** [comment]
Can I take a look at the English translation only? I might have to use Google Translator for the other languages. If yes, please assign this issue to me.

**Comment by adalbertobrant** [comment]
Hi @shehrozsheikh No problema my friend. Please create a README_EN.md and link to the READEME.md using markdown.

**Comment by shehrozsheikh** [comment]
Sure! Can you please assign this issue to me?

**Comment by maenad** [comment]
Hello, can you please assign me for the Spanish version?

**Comment by bhantsi** [comment]
I can do this please assign it to me

**Comment by shehrozsheikh** [comment]
@bhantsi I am already working on the English version, will be creating a PR shortly. You can take lead on the other versions by following the same pattern. :)

**Comment by bhantsi** [comment]
> @bhantsi I am already working on the English version, will be creating a PR shortly. You can take lead on the other versions by following the same pattern. :)

Oh great, let me use google translator for other languages

**Comment by shehrozsheikh** [comment]
@bhantsi I just realized that someone has already created a PR while this issue was assigned to me and I did it in a different way so you can fork the latest repo. and start working on it. :)

**Comment by giovannipessiva** [comment]
Hello, if you are interested in an italian translation I could send you a PR. Let me know!

**Comment by Sandradell** [comment]
Hi! Can I do spanish translation?

**Comment by adalbertobrant** [comment]
@Sandradell spanish , @giovannipessiva Italian

**Comment by adalbertobrant** [comment]
Hello friends @giovannipessiva @shehrozsheikh  @bhantsi  @Sandradell . Could you please give some stars for this repo? Thanks
