### ISSUE TITLE
Add code of conduct in the README file as a link.

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#20]
Happy hacktoberfest 2020 . 

You need to create a link in the README file (all of it) with the code of conduct which is in the same directory.

**Comment by Ashikpaul** [comment]
I can work on this

**Comment by adalbertobrant** [comment]
Sure @Ashikpaul Just edit the README file , do not change another file.

**Comment by adalbertobrant** [comment]
Hi @Ashikpaul Just the english one pls.
