### ISSUE TITLE
Create the BODY MASS INDEX

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#24]
Happy Hacktoberfest 2020

 In the directory indiceCorpoal , create using html , css and javascript a BODY Mass Index.

**Comment by h20190907** [comment]
@adalbertobrant I would like to work on this, could you please assign this to me. Thanks in advance!

**Comment by KhNikh** [comment]
Thanks for sharing. I would like to work on this, could you please assign this to me.

**Comment by adalbertobrant** [comment]
Hello friends , Both could work on this ? @h20190907 and @KhNikh . I have another issue in metabolismo  basal so I think you could also work on it.
There are issues that need the attention to remove some "head" in metabolismo basal in html files. I gonna put this issue and one of you could fix it too.
Please let me know.

**Comment by h20190907** [comment]
@adalbertobrant Could you please reopen this issue. I would like to work on this

**Comment by h20190907** [comment]
@adalbertobrant Please have a look at the changes, and I have also added screenshots for your reference
<img width="1440" alt="Screenshot 2020-11-06 at 7 20 50 PM" src="https://user-images.githubusercontent.com/73196093/98373839-d7d86180-2065-11eb-9e7a-7cb5b89cf543.png">
<img width="1440" alt="Screenshot 2020-11-06 at 7 20 37 PM" src="https://user-images.githubusercontent.com/73196093/98373861-dd35ac00-2065-11eb-9fc6-2f89cb8a35b8.png">
<img width="1440" alt="Screenshot 2020-11-06 at 7 21 54 PM" src="https://user-images.githubusercontent.com/73196093/98373883-e4f55080-2065-11eb-8693-55b16e521f5c.png">

**Comment by h20190907** [comment]
@adalbertobrant Could you please close the issue if everything is done, or suggest to me any changes that I need to make
