### ISSUE TITLE
Fix some mess in html files 

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#26]
Happy Hacktoberfest 2020

 Hi guys and girls .

 Could you please help me fix some errors in html file , there is some ===== and head words....

 See attached pic to understand more. 

 Many thanks and God Bless you All

Ps: what is marked in red should be removed .
![bug-01](https://user-images.githubusercontent.com/6125981/96849136-9f147780-142b-11eb-8443-186e649882e6.png)

**Comment by adalbertobrant** [comment]
There is also a minor error but please do not change javascript file only html file, this minor error I am going to fix my self in the end of Hacktoberfest.

Happy Hacktoberfest 2020

**Comment by Thilagavathi1** [comment]
@adalbertobrant There is an merge conflicts in the html file.so it was rendering like this

**Comment by adalbertobrant** [comment]
Thanks @Thilagavathi1 , that is an easy bug to fix maybe you should also try to fix italian and spanish version and javascript file?

**Comment by adalbertobrant** [comment]
If possible, give me some stars :)

**Comment by Thilagavathi1** [comment]
@adalbertobrant Please check this PR?.let me know if that working as per expectation
