### ISSUE TITLE
Create a Contributors link to the index.html 

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#31]
Dear Friends,  Happy Hacktoberfest 2020

 We are heaving a great time this year with a lot of pull request  , so I why not to create a contributor.html and link to the index html.

Use this https://github.com/adalbertobrant/metabolismobasal/graphs/contributors as an example and create a contributor.html and link it to the index.html

**Comment by nishantschavan** [comment]
i want to work on this . please assign it to me.

**Comment by adalbertobrant** [comment]
Yeap thanks my thank !

**Comment by SaucyGames05** [comment]
I wanna do this

**Comment by adalbertobrant** [comment]
Hello @SaucyGames05  and @nishantschavan maybe you should both work together in this one , what about it ?

**Comment by SaucyGames05** [comment]
So is it just a webpage that lists all the contributors?

**Comment by adalbertobrant** [comment]
@SaucyGames05 that is the webpage => Use this https://github.com/adalbertobrant/metabolismobasal/graphs/contributors  so just and link to index.html

**Comment by SaucyGames05** [comment]
Oh, so we are just adding to the main webpage. Got it, sorry for the confusion lol.

**Comment by SaucyGames05** [comment]
is it just index.html or all versions of the webpage that are in other languages?

**Comment by adalbertobrant** [comment]
@SaucyGames05 No problem but for the javascript create a new function to transform and show metric to imperial .

**Comment by SaucyGames05** [comment]
> @SaucyGames05 No problem but for the javascript create a new function to transform and show metric to imperial .

@adalbertobrant it is a different formula for imperial units so it's easier just to do the same thing but with a different formula than to do imperial to metric.

**Comment by adalbertobrant** [comment]
@SaucyGames05 Ok, but please before you do PR´s check if all the website is working properly

**Comment by SaucyGames05** [comment]
@adalbertobrant No problem.
