### ISSUE TITLE
Unify index html files

### ISSUE THREAD

**Issue by rodbv** [adalbertobrant/metabolismobasal#36]
Currently  every translation has its own index_**.html file which is not very practical, every change/fix has to be copied to the other files manually.

I suggest to have a single html file, and the internationalization can be done with JS.

Here are some  ideas to get that done (there are other ways, this is  just a simple one): add ids to the controls that have to be translated

```
<h1 class="title" id="calculator">Calculadora Taxa Metabólica Basal</h1>
```

Then have some sort  of "dictionary" in  a JS list and change the innerHTML of the controls accordingly, something like

```js
const selectedLanguage = 'pt'; // something the user selected on the screen, for "portuguese"

const dictionary = { 
     'en': { calculate: 'calculate', weight: 'weight' }, 
     'pt': { calculate: 'calcular', weight: 'peso' },
 ...
}

document.getElementById('calculate').innerHTML = dictionary[selectedLanguage]['calculate']
```

It's a nice challenge to learn query selectors etc

Then  to  support new languages a person just have to  add  items to this list dictionary, the language selector on top, and it just works. 

For extra challenge one can get the browser's default language and set accordingly (check `navigator.languages`)

**Comment by eduardopatrick** [comment]
actually, I guess it's better we put in different files for each language

**Comment by eduardopatrick** [comment]
like 
/en-US
 - index.js
/es-ES
 - index.js

**Comment by rodbv** [comment]
what would be in each index.js files? the dictionary like `{ calculate: 'calcular', weight: 'peso' }` and so on?

**Comment by eduardopatrick** [comment]
![image](https://user-images.githubusercontent.com/33517336/97041316-c3fd0d80-1545-11eb-8591-b0ccb0729d6e.png)
my suggestion is more like this, we separe the dictionarys by lang and a external file naming them to be called by a service for example i18n.js file like this: 
![image](https://user-images.githubusercontent.com/33517336/97041722-4f769e80-1546-11eb-9289-c6de765dd6ba.png)
makes sense to you ?

**Comment by rodbv** [comment]
# Yes, good stuff. The ideia is to have 1 HTML file and just swap the strings.

**Comment by eduardopatrick** [comment]
yeah, in Vue, I'm using like this, in js I'll be something like ```t${`phrase`}```
![image](https://user-images.githubusercontent.com/33517336/97054433-29a7c480-155b-11eb-96bd-8962e7bee763.png)

**Comment by adalbertobrant** [comment]
Issued closed. Happy Hacktoberfest 2020 to all , Thanks for the new knowledge and new friends.
