### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by WesleyBSa** [adalbertobrant/metabolismobasal#58]
Customizar o placeholder dos inputs. A impressão na primeira utilização é de que o input já vem preenchido, acredito que pelas cores utilizadas no box, na font do placeholder e na fonte do input.

**Comment by RodivanPeterson** [comment]
Olá, @WesleyBSa! Uma sugestão seria adicionar o texto 'Ex:' (exemplo) antes do número, ao invés de modificar o estilo dos textos dos placeholders. Por exemplo, o campo 'PESO (kg):', o placeholder deste campo em cada idioma ficaria:

- PT: 'Ex: 70'
- EN: 'Ex: 70'
- ES: 'Ej: 70'
- IT: 'Es: 70'

Se essa sugestão for válida, posso fazer essas alterações.

**Comment by devpbleite** [comment]
O projeto ainda está em andamento?

**Comment by RodivanPeterson** [comment]
Olá, bom dia! @devpbleite, não sei dizer, mas eu gostaria de contribuir também. @adalbertobrant, eugostaria de contribuir, tenho uma sugestão para esse problema.
