### ISSUE TITLE
Create a link in the README.md file for the translations

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/metabolismobasal#7]
Hello friends !

This is a first issue for you ! 

Just create a link using markdown to put the translations files (  README.en.md , README.es.md and README.fr.md ) into the README.md

Also modify the translated files names to :

README_EN.md , README_ES.md and README_FR.md

Have a nice hacktoberfest 2020

**Comment by Kunal1198** [comment]
Hi @adalbertobrant Can I work on this?

**Comment by shehrozsheikh** [comment]
Just created a PR, please have a look -> https://github.com/adalbertobrant/metabolismobasal/pull/8

**Comment by Kunal1198** [comment]
Hey @shehrozsheikh How can you create a PR without even getting assigned this issue?

**Comment by shehrozsheikh** [comment]
Actually I worked on the README.md file @Kunal1198 and @adalbertobrant asked for some changes in it, I was working on the changes when the PR got merged, so I just created a new PR with the fixes. So I just checked that there was a new issue for that.

**Comment by przemekdolata96** [comment]
Hi @adalbertobrant I create PR with polish translation.
